### ISSUE TITLE
Alpha Testing Access

### ISSUE THREAD

**Issue by DManstrator** [mobileappdevhm19/apps4students-team2#49]
Hi guys,

I just saw that I was able to become a Tester for your app and I wondered how I am allowed since I can't become a Tester for Team 4's App.

Did you set it to be open for everyone having the link or do you have my GMail address? Would be nice to know so our team can do the same. :)

PS: When trying to download [your app](https://play.google.com/store/apps/details?id=lukas.kirner.gmail.com.apps4students_team2), it says that the requested URL was not found. I guess I have to wait a bit?

Kind regards,

Daniel

**Comment by lukaskirner** [comment]
If you are in the Alpha tester list you are able to join the test and Download the app.
We tested an Internal Share but the links there didn't work immediately.
